name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Installing Dependencies
        run: npm install

      - name: Grant Execute permission to deploy script
        run: chmod +x deploy.sh

      - name: Configure Git Identity
        run: |
          git config user.email "nyakamweaimable@gmail.com"
          git config user.name "nyakamwe"

      - name: Run deploy script
        run: ./deploy.sh
